spring.application.name=moodtrip-backend


spring.r2dbc.url=r2dbc:postgresql://localhost:5432/moodtrip
spring.r2dbc.username=postgres
spring.r2dbc.password=postgres

# Liquibase Configuration
spring.liquibase.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:moodtrip}
spring.liquibase.user=${DB_USERNAME:postgres}
spring.liquibase.password=${DB_PASSWORD:postgres}
spring.liquibase.enabled=false



spring.ai.deepseek.api-key={KEY}
spring.ai.deepseek.chat.options.model=deepseek-chat
spring.ai.deepseek.chat.options.temperature=1.3