spring.application.name=moodtrip-backend
spring.ai.openai.api-key=${OPENAI_API_KEY:dummy-key-for-local}


spring.r2dbc.url=r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:moodtrip}
spring.r2dbc.username=${DB_USERNAME:postgres}
spring.r2dbc.password=${DB_PASSWORD:postgres}

spring.liquibase.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:moodtrip}
spring.liquibase.user=${DB_USERNAME:postgres}
spring.liquibase.password=${DB_PASSWORD:postgres}

